export const MENU_LIST_REQUEST = 'MENU_LIST_REQUEST';
export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_LIST_FAIL = 'MENU_LIST_FAIL';
export const MENU_LIST_RESET = 'MENU_LIST_RESET';


export const MENU_LIST_ID_REQUEST = 'MENU_LIST_ID_REQUEST';
export const MENU_LIST_ID_SUCCESS = 'MENU_LIST_ID_SUCCESS';
export const MENU_LIST_ID_FAIL = 'MENU_LIST_ID_FAIL';
export const MENU_LIST_ID_RESET = 'MENU_LIST_ID_RESET';


export const MENU_DELETE_REQUEST = 'MENU_LIST_REQUEST';
export const MENU_DELETE_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_DELETE_FAIL = 'MENU_LIST_FAIL';
export const MENU_DELETE_RESET = 'MENU_LIST_RESET';


export const MENU_CREATE_REQUEST = 'MENU_CREATE_REQUEST';
export const MENU_CREATE_SUCCESS = 'MENU_CREATE_SUCCESS';
export const MENU_CREATE_FAIL = 'MENU_CREATE_FAIL';
export const MENU_CREATE_RESET = 'MENU_CREATE_RESET';


export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST';
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS';
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL';
export const MENU_DETAILS_RESET = 'MENU_DETAILS_RESET';


export const MENU_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST';
export const MENU_UPDATE_FAIL = 'STORE_UPDATE_FAIL';
export const MENU_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS';
export const MENU_UPDATE_RESET = 'MENU_UPDATE_RESET';